{"name": "Удаление заметки по некорректному ID", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидался статус 404, но получен 409\nassert 409 == 404\n +  where 409 = <Response [409]>.status_code", "trace": "self = <test_api.TestNoteDeletion object at 0x000001FB7C0E3680>, http = <conftest.HttpSession object at 0x000001FB7C1452B0>, base_url = 'http://localhost:3000', invalid_id = '!@#$'\n\n    @allure.title(\"Удаление заметки по некорректному ID\")\n    @pytest.mark.parametrize(\"invalid_id\", [\"invalid_string\", \"123abc\", \"!@#$\"])\n    def test_delete_note_invalid_id(self, http, base_url, invalid_id):\n        with allure.step(f\"Попытка удаления заметки с некорректным ID={invalid_id}\"):\n            response = http.delete(f\"{base_url}/note/{invalid_id}\", timeout=TIMEOUT)\n    \n        # ИСПРАВЛЕНИЕ: Ожидаем 404 вместо 409, т.к. сервер возвращает 404\n>       check_status_code(response, 404)\n\ntests\\test_api.py:376: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [409]>, expected_code = 404\n\n    def check_status_code(response, expected_code: int):\n        \"\"\"Проверка статус кода ответа\"\"\"\n>       assert response.status_code == expected_code, \\\n            f\"Ожидался статус {expected_code}, но получен {response.status_code}\"\nE       AssertionError: Ожидался статус 404, но получен 409\nE       assert 409 == 404\nE        +  where 409 = <Response [409]>.status_code\n\ntests\\test_api.py:11: AssertionError"}, "steps": [{"name": "Попытка удаления заметки с некорректным ID=!@#$", "status": "passed", "start": 1759765433152, "stop": 1759765433153}], "parameters": [{"name": "invalid_id", "value": "'!@#$'"}], "start": 1759765433151, "stop": 1759765433153, "uuid": "5f5156e2-946e-4141-8a8e-67604070f117", "historyId": "a62949cb2723d03952dcd530aefb8a35", "testCaseId": "910e23e9d36a8b6279d9a4800f045aed", "fullName": "tests.test_api.TestNoteDeletion#test_delete_note_invalid_id", "labels": [{"name": "story", "value": "Удаление заметок"}, {"name": "feature", "value": "Управление заметками"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestNoteDeletion"}, {"name": "host", "value": "E4435"}, {"name": "thread", "value": "8244-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}], "titlePath": ["tests", "test_api.py", "TestNoteDeletion"]}