{"name": "Получение заметки по некорректному ID", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидался статус 409, но получен 404\nassert 404 == 409\n +  where 404 = <Response [404]>.status_code", "trace": "self = <test_api.TestNoteRetrieval object at 0x000002628C4A3460>, http = <conftest.HttpSession object at 0x000002628C505940>, base_url = 'http://localhost:3000', invalid_id = '123abc'\n\n    @allure.title(\"Получение заметки по некорректному ID\")\n    @pytest.mark.parametrize(\"invalid_id\", [\"invalid_string\", \"123abc\", \"!@#$\"])\n    def test_get_note_by_invalid_id(self, http, base_url, invalid_id):\n        with allure.step(f\"Попытка получения заметки с некорректным ID={invalid_id}\"):\n            response = http.get(f\"{base_url}/note/{invalid_id}\", timeout=TIMEOUT)\n    \n>       check_status_code(response, 409)\n\ntests\\test_api.py:173: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [404]>, expected_code = 409\n\n    def check_status_code(response, expected_code: int):\n        \"\"\"Проверка статус кода ответа\"\"\"\n>       assert response.status_code == expected_code, \\\n            f\"Ожидался статус {expected_code}, но получен {response.status_code}\"\nE       AssertionError: Ожидался статус 409, но получен 404\nE       assert 404 == 409\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\test_api.py:11: AssertionError"}, "steps": [{"name": "Попытка получения заметки с некорректным ID=123abc", "status": "passed", "start": 1759765318824, "stop": 1759765318826}], "parameters": [{"name": "invalid_id", "value": "'123abc'"}], "start": 1759765318824, "stop": 1759765318826, "uuid": "4d41f778-040a-4131-804a-f2d9b2184132", "historyId": "944c487232783b87fa638e9774e2867b", "testCaseId": "efeb17e83461f5117735527552790e0e", "fullName": "tests.test_api.TestNoteRetrieval#test_get_note_by_invalid_id", "labels": [{"name": "story", "value": "Получение заметок"}, {"name": "feature", "value": "Управление заметками"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestNoteRetrieval"}, {"name": "host", "value": "E4435"}, {"name": "thread", "value": "10656-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}], "titlePath": ["tests", "test_api.py", "TestNoteRetrieval"]}